version: "3.9"

services:
  api:
    build: .
    container_name: loan-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      LOG_LEVEL: ${LOG_LEVEL}  # dynamic per environment
    depends_on:
      - postgres
    ports:
      - "8000:8000"   # expose API for Prometheus
    networks:
      - branch-net

  postgres:
    image: postgres:15
    container_name: branch-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - branch-net

  # --------------------------------
  # PROMETHEUS FOR METRICS SCRAPING
  # --------------------------------
  prometheus:
    image: prom/prometheus
    container_name: loan-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
    networks:
      - branch-net

  # --------------------------------
  #  GRAFANA FOR DASHBOARDS
  # --------------------------------
  grafana:
    image: grafana/grafana
    container_name: loan-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - branch-net

networks:
  branch-net:

volumes:
  postgres-data:
