version: "3.9"

services:
  api:
    build: .
    container_name: loan-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      LOG_LEVEL: ${LOG_LEVEL}  # dynamic per environment
    depends_on:
      - postgres
    networks:
      - branch-net

  postgres:
    image: postgres:15
    container_name: branch-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - branch-net

networks:
  branch-net:

volumes:
  postgres-data:
